# Generated by Django 4.2 on 2023-05-25 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0004_catogery_post_catogery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catogery',
            old_name='title',
            new_name='name',
        ),
    ]
